(define (alpha-quantize filename
                        colors)
    (let* ((image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
           (drawable (car (gimp-image-get-active-layer image))))
        (gimp-layer-add-mask drawable (car (gimp-layer-create-mask drawable ADD-ALPHA-TRANSFER-MASK)))
        (gimp-image-convert-indexed image NO-DITHER MAKE-PALETTE colors FALSE FALSE "")
        (gimp-image-convert-rgb image)
        (gimp-layer-remove-mask drawable MASK-APPLY)
        (gimp-file-save RUN-NONINTERACTIVE image drawable filename filename)
        (gimp-image-delete image)))
